# Numpy 모듈

In [1]:
import numpy
numpy.random.rand(2,2)

array([[0.83260107, 0.80635369],
       [0.03268326, 0.93607019]])

In [2]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
print(a.shape)   # 객체 형태
print(a.ndim)   # 객체 차원
print(a.dtype)     #객체 내부 자료형
print(a.size)

(3,)
1
int32
3


넘파이와 데이터 형

In [9]:
a = np.array([1,2,3],dtype='int32')  #데이터 타입: 32      #항상 대괄호로 묶어줘야함
b = np.array([4,5,6],dtype='int64')   #데이터 타입: 64
c = a + b       # interger가 64로 생성, 행렬 덧셈도 '+'가능
print(c)
print(c.dtype)  

[2 4 6]
int64


In [20]:
b = []
for i in range(0,10,2):
    b.append(i)
b = np.array(b)
print(b)

print(b.max())
print(b.min())
print(b.mean())  #평균

[0 2 4 6 8]
8
0
4.0


In [23]:
a = np.array([[1,1],[2,2],[3,3]])
print(a)
a = a.flatten()  # 평탄화
print(a)

[[1 1]
 [2 2]
 [3 3]]
[1 1 2 2 3 3]


In [27]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[7,8,9]])
print(np.append(a,b))  #평탄화 시켜 더해줌


[1 2 3 4 5 6 7 8 9]


In [33]:
a = np.array([23,45,67,7,2,30,34,82])
print(a.max())
print(b.min())
print(b.mean())

82
19
51.6


In [5]:
b= []
for i in range(10):
    b.append(np.random.randint(0,99))
b = np.array(b)
print(b)
print(b.max())
print(b.min())
print(b.mean())

[26 16 82 82 29 35 96 73 82 49]
96
16
57.0


In [6]:
c = np.append(a,b)
print(c)

[ 1  2  3 26 16 82 82 29 35 96 73 82 49]


In [10]:
a= np.array([[2,3],[1,-2]])
b = np.array([1,4])
print(a.ndim) #nd어래이
np.linalg.det(a)  #determinant


2


-7.000000000000001

In [12]:
a = np.array([1,2,3])
b= np.array([4,5,6])
c = a + b
c

array([5, 7, 9])

shape 가 다를 경우 -> value Error

In [15]:
a = np.array([1,2])
b = np.array([4,5,6])
try:
    c = a+b
except:
    print('에러가 발생')

에러가 발생


# 행렬의 곱

In [22]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

b = np.array([[2,2,2],[2,2,2],[2,2,2]])  #행렬연산

print(a * b)  #그냥 곱
print()
print(a @ b) #행렬의 곱
print()
print(a**2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[12 12 12]
 [30 30 30]
 [48 48 48]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [28]:
print(np.zeros((2,3)))   #괄호 2개
print(np.ones((2,3)))
print(np.full((2,3),100))
print(np.eye(3))
print(np.random.random((2,3)))


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[100 100 100]
 [100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.44075322 0.57078199 0.68888822]
 [0.72902236 0.19564348 0.937673  ]]


In [29]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [31]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [32]:
np.arange(0.0,1.0,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [33]:
np.linspace(0,10,5)   #동일한 간격

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# 실습

In [34]:
a1 = np.full((3,3),2)
print(a1)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [36]:
a2 = np.arange(1,13)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
a3 = np.arange(3,51,3)
print(a3)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [40]:
a4 = np.linspace(0,20,5)
print(a4)

[ 0.  5. 10. 15. 20.]


배열의 재구성(reshape)

In [41]:
a = np.arange(0,10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [42]:
b = np.arange(0,10).reshape(5,2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [43]:
c = np.arange(0,1).reshape(3,3)
print(c)

ValueError: cannot reshape array of size 1 into shape (3,3)

# 실습

In [44]:
a1 = np.arange(1,13)
a1 = a1.reshape(2,6)
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [45]:
a2 = np.arange(1,31)
a2 = a2.reshape(3,10)
print(a2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [46]:
a3 = a2.reshape(6,5)
print(a3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [47]:
a4 = a3.transpose()
print(a4)

[[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


# 다차원 배열의 축

In [53]:
a = np.arange(0,6).reshape(3,2)
print(a)
print(a.sum())
print(a.sum(axis=0))  #열로 더함
print(a.sum(axis=1))  #행으로 더함
print(a.max(axis=0))  #열에서 가장 큰 값
print(a.max(axis=1))  #행에서 가장 큰 값

[[0 1]
 [2 3]
 [4 5]]
15
[6 9]
[1 5 9]
[4 5]
[1 3 5]


In [78]:
a = np.array([1,3,4])
print(np.insert(a,1,2))  #첫번째에 2를 넣음

a = np.array([[1,1],[2,2],[3,3]])
print(np.insert(a,6,4))
a = np.array([[1,1],[2,2],[3,3]])
print(np.insert(a,6,[4,4]))


[1 2 3 4]
[1 1 2 2 3 3 4]
[1 1 2 2 3 3 4 4]


# 실습

In [ ]:
a = []
for i in range(15):
    a.append(np.random.randint(1,100))
a = np.array(a).reshape(3,5)
print(a)


위 방식으로도 풀 수 있으나, 아래 방식이 훨씬 간단함

In [69]:
a = np.random.randint(1,100,size=15).reshape(3,5)
print(a)

[[85 46 28 41 23]
 [ 5  7 54 82 26]
 [ 1 78 54  2 12]]


In [70]:
print('a의 열방향 최댓값:',a.max(axis=0))
print('a의 열방향 최솟값:',a.min(axis=0))
print('a의 열방향 평균:',a.mean(axis=0))

a의 열방향 최댓값: [85 78 54 82 26]
a의 열방향 최솟값: [ 1  7 28  2 12]
a의 열방향 평균: [30.33333333 43.66666667 45.33333333 41.66666667 20.33333333]


In [71]:
print('a의 행방향 최댓값:',a.max(axis=1))
print('a의 행방향 최솟값:',a.min(axis=1))
print('a의 행방향 평균:',a.mean(axis=1))

a의 행방향 최댓값: [85 82 78]
a의 행방향 최솟값: [23  5  1]
a의 행방향 평균: [44.6 34.8 29.4]


자료의 인덱싱 과 슬라이스

In [79]:
a = np.array([1,2,3])
print(a[0],a[1],a[2])


1 2 3


In [81]:
a = np.array([1,2,3,4,5])
print(a[np.array([0,1])])
print(a[np.array([0,1,2])])
print(a[np.array([0,1,3])])

[1 2]
[1 2 3]
[1 2 4]


In [82]:
a = np.array([1,2,3,4,5,6,7,8])
print(a[1:5])
print(a[1:])
print(a[:])
print(a[::2])

array([2, 3, 4, 5])

In [86]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
print(np.array([a[1],a[3],a[5],a[7]]))

[2 4 6 8]


In [88]:
b = np.array([a[5:]])
print(b)

[[ 6  7  8  9 10]]


# 2차원 배열의 인덱싱

In [89]:
a = np.arange(0,24).reshape(4,3,2)  #4행으로 3열의 2개씩의 2차원
print(a)


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


## iterator

In [91]:
list_ = [10,20,30,40,50]
print(type(list_))
lit_ = iter(list_)
print(type(lit_))

<class 'list'>
<class 'list_iterator'>


In [92]:
next(lit_)

10

In [93]:
next(lit_)

20

In [94]:
next(lit_)

30

In [95]:
next(lit_)

40

In [96]:
next(lit_)

50

In [97]:
next(lit_)

StopIteration: 

In [103]:
list_ = [1,2,3,4,5]
lit_ = iter(list_)
lit_.__next__()
lit_.__next__()
lit_.__next__()

3

# OddCounter

In [108]:
class OddCounter:
    def __init__(self, n = 1):
        self.n = n
    def __iter__(self):
        return self
    def __next__(self):
        t = self.n
        self.n +=2
        return t

my_counter = OddCounter()
print(next(my_counter))
print(next(my_counter))
print(next(my_counter))
print(my_counter.__next__())

1
3
5
7


# set 함수는 공부하기